import { Agent, AgentMessage, AgentWorkHistory } from "@/types/agent";

export const DUMMY_AGENTS: Agent[] = [
  {
    id: "PM",
    name: "Project Manager",
    role: "업무 분배 · 일정 관리",
    status: "active",
    avatar: "PM",
    color: "#8B5CF6",
    currentTask: "epic-1 진행 현황 모니터링",
    currentTicketId: null,
    currentEpicId: "epic-1",
    todayCostUsd: 3.2,
    todayCompletedTickets: 0,
    primaryModel: "claude-haiku",
  },
  {
    id: "GM",
    name: "Governance Manager",
    role: "거버넌스 · 접근 정책",
    status: "active",
    avatar: "GM",
    color: "#F97316",
    currentTask: "users 테이블 접근 정책 검토",
    currentTicketId: "ticket-6",
    currentEpicId: "epic-1",
    todayCostUsd: 2.8,
    todayCompletedTickets: 1,
    primaryModel: "claude-haiku",
  },
  {
    id: "SM",
    name: "Spec Manager",
    role: "기술 스펙 결정",
    status: "idle",
    avatar: "SM",
    color: "#3B82F6",
    currentTask: null,
    currentTicketId: null,
    currentEpicId: null,
    todayCostUsd: 5.1,
    todayCompletedTickets: 2,
    primaryModel: "claude-sonnet-4",
  },
  {
    id: "Dsn",
    name: "Designer",
    role: "UI 디자인 수행",
    status: "active",
    avatar: "Ds",
    color: "#EC4899",
    currentTask: "이미지 뷰어 UI 시안 작업",
    currentTicketId: "ticket-5",
    currentEpicId: "epic-1",
    todayCostUsd: 12.4,
    todayCompletedTickets: 1,
    primaryModel: "gpt-4o",
  },
  {
    id: "Pln",
    name: "Planner",
    role: "기획서 제작 · 티켓 생성",
    status: "idle",
    avatar: "Pl",
    color: "#10B981",
    currentTask: null,
    currentTicketId: null,
    currentEpicId: null,
    todayCostUsd: 0.9,
    todayCompletedTickets: 3,
    primaryModel: "gemini-2.0-flash",
  },
  {
    id: "FE",
    name: "Front-end Developer",
    role: "프론트엔드 개발",
    status: "active",
    avatar: "FE",
    color: "#06B6D4",
    currentTask: "ImageUploader 컴포넌트 리팩토링",
    currentTicketId: "ticket-3",
    currentEpicId: "epic-1",
    todayCostUsd: 18.4,
    todayCompletedTickets: 1,
    primaryModel: "claude-sonnet-4",
  },
  {
    id: "BE",
    name: "Back-end Developer",
    role: "백엔드 개발",
    status: "active",
    avatar: "BE",
    color: "#6366F1",
    currentTask: "공유 링크 생성 API 개발",
    currentTicketId: "ticket-6",
    currentEpicId: "epic-1",
    todayCostUsd: 32.1,
    todayCompletedTickets: 2,
    primaryModel: "claude-sonnet-4",
  },
  {
    id: "BM",
    name: "Budget Manager",
    role: "토큰 · 인력 비용 평가",
    status: "idle",
    avatar: "BM",
    color: "#EAB308",
    currentTask: null,
    currentTicketId: null,
    currentEpicId: null,
    todayCostUsd: 0.8,
    todayCompletedTickets: 0,
    primaryModel: "gemini-2.0-flash",
  },
  {
    id: "HR",
    name: "HR Manager",
    role: "인력 자원 제안",
    status: "idle",
    avatar: "HR",
    color: "#14B8A6",
    currentTask: null,
    currentTicketId: null,
    currentEpicId: null,
    todayCostUsd: 0.6,
    todayCompletedTickets: 0,
    primaryModel: "claude-haiku",
  },
];

export const DUMMY_AGENT_MESSAGES: AgentMessage[] = [
  {
    id: "msg-1",
    fromAgent: "PM",
    toAgent: "FE",
    content: "ticket-3 작업 현황 업데이트 요청. ETA 언제로 잡으면 될까요?",
    timestamp: "2026-04-03T09:05:00Z",
    ticketId: "ticket-3",
  },
  {
    id: "msg-2",
    fromAgent: "FE",
    toAgent: "PM",
    content: "오늘 오후 5시 완료 예정입니다. 코드 리뷰 HITL 발행 후 Done 처리하겠습니다.",
    timestamp: "2026-04-03T09:07:00Z",
    ticketId: "ticket-3",
  },
  {
    id: "msg-3",
    fromAgent: "GM",
    toAgent: "BE",
    content: "ticket-6에서 users 테이블 접근이 필요하시죠? HITL 발행했습니다. 승인 대기 중입니다.",
    timestamp: "2026-04-03T10:31:00Z",
    ticketId: "ticket-6",
  },
  {
    id: "msg-4",
    fromAgent: "BE",
    toAgent: "GM",
    content: "확인했습니다. user_id, display_name 컬럼만 읽기 용도로 사용합니다.",
    timestamp: "2026-04-03T10:33:00Z",
    ticketId: "ticket-6",
  },
  {
    id: "msg-5",
    fromAgent: "SM",
    toAgent: "FE",
    content: "React DnD 대신 네이티브 Drag API 사용 권장합니다. 번들 크기 절감 효과가 있습니다.",
    timestamp: "2026-04-03T08:45:00Z",
    ticketId: "ticket-3",
  },
  {
    id: "msg-6",
    fromAgent: "FE",
    toAgent: "SM",
    content: "반영했습니다. 브라우저 호환성 이슈는 폴리필로 처리했습니다.",
    timestamp: "2026-04-03T08:52:00Z",
    ticketId: "ticket-3",
  },
  {
    id: "msg-7",
    fromAgent: "Dsn",
    toAgent: "FE",
    content: "이미지 뷰어 시안 공유드립니다. 모달 오버레이 방식으로 확정했습니다.",
    timestamp: "2026-04-03T08:00:00Z",
    ticketId: "ticket-5",
  },
  {
    id: "msg-8",
    fromAgent: "PM",
    toAgent: "BE",
    content: "공유 링크 API, S3 pre-signed URL 방식으로 구현 부탁드립니다. SM과 스펙 조율 완료.",
    timestamp: "2026-04-03T09:30:00Z",
    ticketId: "ticket-6",
  },
  {
    id: "msg-9",
    fromAgent: "BM",
    toAgent: "PM",
    content: "오늘 예상 비용 $75.3입니다. 이번 에픽 예산 대비 62% 소진 중입니다.",
    timestamp: "2026-04-03T09:00:00Z",
  },
  {
    id: "msg-10",
    fromAgent: "PM",
    toAgent: "SM",
    content: "epic-1 완료 후 다음 에픽 스펙 정의 시작해주세요. Pln과 협력해주시기 바랍니다.",
    timestamp: "2026-04-03T11:00:00Z",
  },
];

export const DUMMY_AGENT_WORK_HISTORY: AgentWorkHistory[] = [
  // FE 작업 이력
  {
    id: "wh-1",
    agentId: "FE",
    ticketId: "ticket-3",
    ticketTitle: "ImageUploader 컴포넌트 개발",
    action: "진행 중 → 검토 요청 (HITL 발행)",
    timestamp: "2026-04-03T09:00:00Z",
    durationMin: 180,
    costUsd: 18.4,
  },
  {
    id: "wh-2",
    agentId: "FE",
    ticketId: "ticket-2",
    ticketTitle: "이미지 업로드 API 연동",
    action: "완료",
    timestamp: "2026-04-02T16:00:00Z",
    durationMin: 120,
    costUsd: 14.2,
  },
  // BE 작업 이력
  {
    id: "wh-3",
    agentId: "BE",
    ticketId: "ticket-6",
    ticketTitle: "공유 링크 생성 API",
    action: "진행 중",
    timestamp: "2026-04-03T10:00:00Z",
    durationMin: 90,
    costUsd: 32.1,
  },
  {
    id: "wh-4",
    agentId: "BE",
    ticketId: "ticket-4",
    ticketTitle: "이미지 메타데이터 저장",
    action: "완료",
    timestamp: "2026-04-02T14:00:00Z",
    durationMin: 150,
    costUsd: 28.5,
  },
  {
    id: "wh-5",
    agentId: "BE",
    ticketId: "ticket-1",
    ticketTitle: "S3 업로드 모듈 구현",
    action: "완료",
    timestamp: "2026-04-01T17:00:00Z",
    durationMin: 200,
    costUsd: 35.0,
  },
  // Dsn 작업 이력
  {
    id: "wh-6",
    agentId: "Dsn",
    ticketId: "ticket-5",
    ticketTitle: "이미지 공유 UI 시안",
    action: "검토 요청 (HITL 발행)",
    timestamp: "2026-04-03T08:00:00Z",
    durationMin: 120,
    costUsd: 12.4,
  },
  {
    id: "wh-7",
    agentId: "Dsn",
    ticketId: "ticket-2",
    ticketTitle: "업로드 진행 상태 UI",
    action: "완료",
    timestamp: "2026-04-02T11:00:00Z",
    durationMin: 90,
    costUsd: 9.8,
  },
  // GM 작업 이력
  {
    id: "wh-8",
    agentId: "GM",
    ticketId: "ticket-6",
    ticketTitle: "users 테이블 접근 정책 검토",
    action: "HITL 발행 (승인 대기)",
    timestamp: "2026-04-03T10:30:00Z",
    durationMin: 30,
    costUsd: 2.8,
  },
  // SM 작업 이력
  {
    id: "wh-9",
    agentId: "SM",
    ticketId: "ticket-1",
    ticketTitle: "이미지 스토리지 스펙 결정",
    action: "완료 (CDN + 리사이징 채택)",
    timestamp: "2026-04-01T15:30:00Z",
    durationMin: 60,
    costUsd: 5.1,
  },
  // Pln 작업 이력
  {
    id: "wh-10",
    agentId: "Pln",
    ticketId: "ticket-1",
    ticketTitle: "이미지 공유 기능 기획서",
    action: "완료",
    timestamp: "2026-04-01T10:00:00Z",
    durationMin: 45,
    costUsd: 0.9,
  },
];
