import { ExternalWorkProposal, ExternalWork, ExternalEarningsSummary } from "@/types/external";

export const DUMMY_EXTERNAL_PROPOSALS: ExternalWorkProposal[] = [
  {
    id: "ext-prop-1",
    title: "React Native 컴포넌트 코드 리뷰",
    description:
      "신규 개발한 React Native 컴포넌트(20개) 코드 리뷰 요청. 성능, 가독성, 베스트 프랙티스 기준으로 검토 부탁드립니다. TypeScript strict 모드 적용 여부도 확인 필요.",
    requiredExpertise: ["React Native", "TypeScript", "모바일 성능 최적화"],
    hourlyRate: 50,
    estimatedHours: 3,
    urgency: "medium",
    postedAt: "2026-04-03T08:00:00Z",
    deadline: "2026-04-07T18:00:00Z",
    clientCompany: "스타트업 A",
    clientContact: "박대표",
    matchScore: 91,
    recommendedAssignee: "user-2",
    aiAssistLevel: "assisted",
  },
  {
    id: "ext-prop-2",
    title: "REST API 설계 검토 및 문서화",
    description:
      "이커머스 백오피스 API 설계 검토 요청. 현재 설계된 엔드포인트 15개에 대해 RESTful 원칙 준수 여부, 인증/인가 구조, 응답 포맷 일관성을 검토해주세요. Swagger 문서화도 함께 요청드립니다.",
    requiredExpertise: ["REST API", "Node.js", "OpenAPI/Swagger"],
    hourlyRate: 60,
    estimatedHours: 4,
    urgency: "high",
    postedAt: "2026-04-03T07:30:00Z",
    deadline: "2026-04-05T12:00:00Z",
    clientCompany: "스타트업 B",
    clientContact: "김CTO",
    matchScore: 87,
    recommendedAssignee: "user-2",
    aiAssistLevel: "assisted",
  },
  {
    id: "ext-prop-3",
    title: "Figma → React 컴포넌트 변환",
    description:
      "디자인 시스템 Figma 파일 기반으로 React 공통 컴포넌트 30개 개발 요청. shadcn/ui 기반으로 작성, Storybook 문서화 포함. 반응형 필수.",
    requiredExpertise: ["React", "Figma", "Tailwind CSS", "Storybook"],
    hourlyRate: 45,
    estimatedHours: 20,
    urgency: "low",
    postedAt: "2026-04-02T15:00:00Z",
    deadline: "2026-04-20T18:00:00Z",
    clientCompany: "에이전시 C",
    clientContact: "이팀장",
    matchScore: 78,
    recommendedAssignee: "user-3",
    aiAssistLevel: "full",
  },
  {
    id: "ext-prop-4",
    title: "PostgreSQL 쿼리 최적화 컨설팅",
    description:
      "DAU 10만 서비스의 슬로우 쿼리 개선 컨설팅. 현재 평균 응답 시간 2.3초를 500ms 이하로 단축하는 것이 목표입니다. 인덱스 설계, 파티셔닝, 캐싱 전략 포함.",
    requiredExpertise: ["PostgreSQL", "쿼리 최적화", "인덱스 설계"],
    hourlyRate: 80,
    estimatedHours: 6,
    urgency: "high",
    postedAt: "2026-04-03T09:00:00Z",
    deadline: "2026-04-06T18:00:00Z",
    clientCompany: "핀테크 D",
    clientContact: "최아키텍트",
    matchScore: 82,
    recommendedAssignee: "user-1",
    aiAssistLevel: "assisted",
  },
];

export const DUMMY_EXTERNAL_ACTIVE: ExternalWork[] = [
  {
    id: "ext-work-1",
    proposalId: undefined,
    title: "Vue.js → React 컴포넌트 마이그레이션",
    description: "기존 Vue.js 2.x 코드베이스의 핵심 컴포넌트 15개를 React 18로 마이그레이션. Composition API 패턴 → React Hooks 전환.",
    clientCompany: "미디어 C",
    clientContact: "정팀장",
    hourlyRate: 55,
    hoursWorked: 4,
    totalHours: 8,
    status: "in_progress",
    assigneeId: "user-2",
    assigneeName: "이시니어",
    startedAt: "2026-04-01T14:00:00Z",
    paymentStatus: "pending",
    deliverables: ["마이그레이션된 컴포넌트 15개", "마이그레이션 가이드 문서"],
    aiAssistLevel: "assisted",
  },
  {
    id: "ext-work-2",
    title: "CI/CD 파이프라인 설계 자문",
    description: "GitHub Actions 기반 CI/CD 파이프라인 설계 및 초기 구축 자문. 테스트 자동화, 스테이징/프로덕션 배포 분리.",
    clientCompany: "SaaS E",
    clientContact: "한개발자",
    hourlyRate: 70,
    hoursWorked: 2,
    totalHours: 5,
    status: "in_progress",
    assigneeId: "user-1",
    assigneeName: "김CTO",
    startedAt: "2026-04-02T10:00:00Z",
    paymentStatus: "pending",
    deliverables: ["CI/CD 설계 문서", "GitHub Actions 워크플로우 파일"],
    aiAssistLevel: "human_only",
  },
];

export const DUMMY_EXTERNAL_COMPLETED: ExternalWork[] = [
  {
    id: "ext-done-1",
    title: "Next.js 성능 감사 및 최적화",
    clientCompany: "쇼핑몰 F",
    clientContact: "김대표",
    hourlyRate: 65,
    hoursWorked: 5,
    totalHours: 5,
    status: "completed",
    assigneeId: "user-2",
    assigneeName: "이시니어",
    startedAt: "2026-03-25T09:00:00Z",
    completedAt: "2026-03-27T17:00:00Z",
    paymentStatus: "paid",
    totalEarnings: 325,
    deliverables: ["성능 감사 리포트", "최적화 PR 3개"],
    aiAssistLevel: "assisted",
  },
  {
    id: "ext-done-2",
    title: "TypeScript 타입 시스템 설계",
    clientCompany: "스타트업 G",
    clientContact: "이CTO",
    hourlyRate: 60,
    hoursWorked: 3,
    totalHours: 3,
    status: "completed",
    assigneeId: "user-3",
    assigneeName: "김주니어",
    startedAt: "2026-03-20T14:00:00Z",
    completedAt: "2026-03-21T12:00:00Z",
    paymentStatus: "requested",
    totalEarnings: 180,
    deliverables: ["타입 정의 파일 세트", "마이그레이션 가이드"],
    aiAssistLevel: "full",
  },
  {
    id: "ext-done-3",
    title: "데이터베이스 스키마 리뷰",
    clientCompany: "헬스케어 H",
    clientContact: "박아키텍트",
    hourlyRate: 75,
    hoursWorked: 2,
    totalHours: 2,
    status: "completed",
    assigneeId: "user-1",
    assigneeName: "김CTO",
    startedAt: "2026-03-15T10:00:00Z",
    completedAt: "2026-03-15T16:00:00Z",
    paymentStatus: "paid",
    totalEarnings: 150,
    deliverables: ["스키마 리뷰 리포트", "개선 권고안"],
    aiAssistLevel: "human_only",
  },
];

export const DUMMY_EARNINGS_SUMMARY: ExternalEarningsSummary = {
  totalEarnings: 655,
  thisMonthEarnings: 655,
  pendingPayment: 180,
  completedCount: 3,
  inProgressCount: 2,
};
