import { HITLQueueItem } from "@/types/hitl";

export const DUMMY_HITL_QUEUE: HITLQueueItem[] = [
  {
    id: "hitl-1",
    type: "code_review",
    title: "ImageUploader 컴포넌트 코드 리뷰",
    ticketId: "ticket-3",
    epicId: "epic-1",
    priority: "high",
    status: "waiting",
    createdAt: "2026-04-03T09:00:00Z",
    requestedBy: "FE",
    assignedTo: { id: "user-3", name: "김주니어", level: "L1" },
    briefing:
      "FE Agent가 ImageUploader 컴포넌트를 작성했습니다. 기존 FileUploader를 확장하여 이미지 미리보기, 드래그앤드롭, 멀티 업로드를 지원합니다.",
    relatedFiles: ["src/components/ImageUploader.tsx", "src/components/FileUploader.tsx"],
    agentDiscussionSummary: "SM이 React DnD 대신 네이티브 Drag API 사용을 권장. FE가 수용하여 구현.",
  },
  {
    id: "hitl-2",
    type: "security_approval",
    title: "users 테이블 user_id 참조 승인",
    ticketId: "ticket-6",
    epicId: "epic-1",
    priority: "high",
    status: "waiting",
    createdAt: "2026-04-03T10:30:00Z",
    requestedBy: "GM",
    assignedTo: { id: "user-1", name: "김CTO", level: "L3" },
    briefing:
      "이미지 공유 기능 개발에 users 테이블의 user_id 참조가 필요합니다. 해당 컬럼은 로우 데이터로 분류되어 있어 L3 승인이 필요합니다.",
    dataAccessRequest: {
      table: "users",
      columns: ["user_id", "display_name"],
      purpose: "이미지 소유자 표시",
      duration: "ticket-6 완료 시까지",
    },
  },
  {
    id: "hitl-3",
    type: "spec_decision",
    title: "이미지 스토리지 스펙 선택",
    ticketId: "ticket-1",
    epicId: "epic-1",
    priority: "medium",
    status: "approved",
    createdAt: "2026-04-01T14:00:00Z",
    completedAt: "2026-04-01T15:30:00Z",
    requestedBy: "SM",
    assignedTo: { id: "user-1", name: "김CTO", level: "L3" },
    briefing: "이미지 스토리지 방식 3가지 옵션입니다.",
    options: [
      { id: "opt-a", label: "S3 직접 업로드", cost: "$15/월", risk: "낮음", devDays: 2 },
      { id: "opt-b", label: "CDN + 리사이징 파이프라인", cost: "$25/월", risk: "낮음", devDays: 4, recommended: true },
      { id: "opt-c", label: "기존 파일 서버 활용", cost: "$0", risk: "높음 (DAU 증가 시 병목)", devDays: 1 },
    ],
    selectedOption: "opt-b",
  },
  {
    id: "hitl-4",
    type: "assignment",
    title: "코드 리뷰 담당자 배정",
    ticketId: "ticket-3",
    epicId: "epic-1",
    priority: "medium",
    status: "approved",
    createdAt: "2026-04-02T11:00:00Z",
    completedAt: "2026-04-02T11:20:00Z",
    requestedBy: "HR",
    assignedTo: { id: "user-1", name: "김CTO", level: "L3" },
    briefing: "ImageUploader 코드 리뷰 담당자를 추천합니다.",
    candidates: [
      {
        type: "internal",
        id: "user-3",
        name: "김주니어",
        level: "L1",
        matchScore: 72,
        availability: "오늘 오후 가용",
        costPerHour: 0,
        note: "파일 업로드 경험 없음, 맥락 이해도 낮음",
        reworkRisk: "40%",
      },
      {
        type: "internal",
        id: "user-2",
        name: "이시니어",
        level: "L2",
        matchScore: 95,
        availability: "내일 오전 가용",
        costPerHour: 0,
        note: "현재 다른 티켓 리뷰 중",
      },
      {
        type: "external",
        id: "ext-1",
        name: "박프론트",
        expertise: "React 전문",
        matchScore: 91,
        availability: "즉시 가용",
        costPerHour: 45,
        note: "유사 프로젝트 3건 경험",
      },
    ],
    selectedCandidate: "user-3",
  },
  {
    id: "hitl-5",
    type: "design_review",
    title: "이미지 공유 UI 디자인 검토",
    ticketId: "ticket-5",
    epicId: "epic-1",
    priority: "medium",
    status: "waiting",
    createdAt: "2026-04-03T08:00:00Z",
    requestedBy: "Dsn",
    assignedTo: { id: "user-1", name: "김CTO", level: "L3" },
    briefing:
      "Dsn Agent가 이미지 공유 UI 시안을 완성했습니다. 기존 디자인 시스템의 카드 컴포넌트 기반으로 작성했습니다.",
    designUrl: "https://figma.com/mock-design",
  },
  {
    id: "hitl-6",
    type: "model_allocation",
    title: "이미지 공유 기능 — AI 모델 배분 확인",
    epicId: "epic-1",
    priority: "high",
    status: "waiting",
    createdAt: "2026-04-03T08:30:00Z",
    requestedBy: "SM",
    assignedTo: { id: "user-1", name: "김CTO", level: "L3" },
    briefing: "이미지 공유 기능 개발에 투입될 AI 모델 배분을 확인해주세요.",
    allocation: {
      agents: [
        {
          agentId: "FE",
          models: [
            { model: "claude-sonnet-4", ratio: 0.78, estimatedInputTokens: 187200, estimatedOutputTokens: 66300, estimatedCost: 18.4 },
            { model: "gpt-4o", ratio: 0.15, estimatedInputTokens: 36000, estimatedOutputTokens: 12750, estimatedCost: 6.2 },
            { model: "gemini-2.0-flash", ratio: 0.07, estimatedInputTokens: 16800, estimatedOutputTokens: 5950, estimatedCost: 0.4 },
          ],
          totalCost: 25.0,
        },
        {
          agentId: "BE",
          models: [
            { model: "claude-sonnet-4", ratio: 0.9, estimatedInputTokens: 342000, estimatedOutputTokens: 108000, estimatedCost: 32.1 },
            { model: "gemini-2.0-flash", ratio: 0.1, estimatedInputTokens: 38000, estimatedOutputTokens: 12000, estimatedCost: 0.9 },
          ],
          totalCost: 33.0,
        },
        {
          agentId: "Dsn",
          models: [
            { model: "claude-sonnet-4", ratio: 0.55, estimatedInputTokens: 88000, estimatedOutputTokens: 33000, estimatedCost: 8.2 },
            { model: "gpt-4o", ratio: 0.45, estimatedInputTokens: 72000, estimatedOutputTokens: 27000, estimatedCost: 11.8 },
          ],
          totalCost: 20.0,
        },
        {
          agentId: "support",
          label: "지원 Agent (PM/GM/Pln/SM/HR/BM)",
          models: [
            { model: "gemini-2.0-flash", ratio: 0.8, estimatedCost: 1.2 },
            { model: "claude-haiku", ratio: 0.2, estimatedCost: 0.8 },
          ],
          totalCost: 2.0,
        },
      ],
      totalCost: 80.0,
      alternatives: [
        { id: "alt-current", label: "현재 구성 (권장)", totalCost: 80.0, qualityImpact: "none", recommended: true },
        { id: "alt-budget", label: "Sonnet → Haiku 전환", totalCost: 34.0, qualityImpact: "moderate_decrease" },
        { id: "alt-minimum", label: "전체 Flash 통일", totalCost: 12.0, qualityImpact: "significant_decrease" },
      ],
      smComment:
        "코드 생성 작업에 Sonnet을 집중 배치했습니다. 디자인 작업은 GPT-4o의 이미지 이해 능력을 활용합니다. 단순 분류/정리 작업은 Flash로 비용을 절감합니다.",
    },
  },
];
