import { HITLQueueItem } from "@/types/hitl";

export const DUMMY_HITL_QUEUE: HITLQueueItem[] = [
  {
    id: "hitl-1",
    type: "code_review",
    title: "ImageUploader 컴포넌트 코드 리뷰",
    ticketId: "ticket-3",
    epicId: "epic-1",
    priority: "high",
    status: "waiting",
    createdAt: "2026-04-03T09:00:00Z",
    requestedBy: "FE",
    assignedTo: { id: "user-3", name: "김주니어", level: "L1" },
    briefing:
      "FE Agent가 ImageUploader 컴포넌트를 작성했습니다. 기존 FileUploader를 확장하여 이미지 미리보기, 드래그앤드롭, 멀티 업로드를 지원합니다.",
    relatedFiles: ["src/components/ImageUploader.tsx", "src/components/FileUploader.tsx"],
    agentDiscussionSummary: "SM이 React DnD 대신 네이티브 Drag API 사용을 권장. FE가 수용하여 구현.",
    confidence: 87,
    riskLevel: "medium",
    beforeAfterDiff: {
      before: "// FileUploader.tsx — 단일 파일 업로드만 지원\nexport function FileUploader({ onUpload }) {\n  return <input type='file' onChange={onUpload} />;\n}",
      after: "// ImageUploader.tsx — 멀티 업로드 + 드래그앤드롭 + 미리보기\nexport function ImageUploader({ onUpload, maxFiles = 10 }) {\n  const [previews, setPreviews] = useState([]);\n  // ... DnD + preview logic\n}",
      addedLines: 342,
      removedLines: 89,
    },
    evidenceNotes: [
      { metric: "번들 크기", current: "2.4MB", proposed: "2.6MB", impact: "negative" },
      { metric: "테스트 커버리지", current: "71%", proposed: "84%", impact: "positive" },
      { metric: "브라우저 호환성", current: "Chrome/Safari", proposed: "Chrome/Safari/Firefox", impact: "positive" },
    ],
  },
  {
    id: "hitl-2",
    type: "security_approval",
    title: "users 테이블 user_id 참조 승인",
    ticketId: "ticket-6",
    epicId: "epic-1",
    priority: "high",
    status: "waiting",
    createdAt: "2026-04-03T10:30:00Z",
    requestedBy: "GM",
    assignedTo: { id: "user-1", name: "김CTO", level: "L3" },
    briefing:
      "이미지 공유 기능 개발에 users 테이블의 user_id 참조가 필요합니다. 해당 컬럼은 로우 데이터로 분류되어 있어 L3 승인이 필요합니다.",
    dataAccessRequest: {
      table: "users",
      columns: ["user_id", "display_name"],
      purpose: "이미지 소유자 표시",
      duration: "ticket-6 완료 시까지",
    },
    confidence: 72,
    riskLevel: "high",
    evidenceNotes: [
      { metric: "데이터 분류", current: "로우 데이터", proposed: "읽기 전용 접근", impact: "neutral" },
      { metric: "접근 범위", current: "없음", proposed: "user_id, display_name", impact: "negative" },
      { metric: "감사 로그", current: "미적용", proposed: "모든 쿼리 기록", impact: "positive" },
    ],
  },
  {
    id: "hitl-3",
    type: "spec_decision",
    title: "이미지 스토리지 스펙 선택",
    ticketId: "ticket-1",
    epicId: "epic-1",
    priority: "medium",
    status: "approved",
    createdAt: "2026-04-01T14:00:00Z",
    completedAt: "2026-04-01T15:30:00Z",
    requestedBy: "SM",
    assignedTo: { id: "user-1", name: "김CTO", level: "L3" },
    briefing: "이미지 스토리지 방식 3가지 옵션입니다.",
    options: [
      { id: "opt-a", label: "S3 직접 업로드", cost: "$15/월", risk: "낮음", devDays: 2 },
      { id: "opt-b", label: "CDN + 리사이징 파이프라인", cost: "$25/월", risk: "낮음", devDays: 4, recommended: true },
      { id: "opt-c", label: "기존 파일 서버 활용", cost: "$0", risk: "높음 (DAU 증가 시 병목)", devDays: 1 },
    ],
    selectedOption: "opt-b",
  },
  {
    id: "hitl-4",
    type: "assignment",
    title: "코드 리뷰 담당자 배정",
    ticketId: "ticket-3",
    epicId: "epic-1",
    priority: "medium",
    status: "approved",
    createdAt: "2026-04-02T11:00:00Z",
    completedAt: "2026-04-02T11:20:00Z",
    requestedBy: "HR",
    assignedTo: { id: "user-1", name: "김CTO", level: "L3" },
    briefing: "ImageUploader 코드 리뷰 담당자를 추천합니다.",
    candidates: [
      {
        type: "internal",
        id: "user-3",
        name: "김주니어",
        level: "L1",
        matchScore: 72,
        availability: "오늘 오후 가용",
        costPerHour: 0,
        note: "파일 업로드 경험 없음, 맥락 이해도 낮음",
        reworkRisk: "40%",
      },
      {
        type: "internal",
        id: "user-2",
        name: "이시니어",
        level: "L2",
        matchScore: 95,
        availability: "내일 오전 가용",
        costPerHour: 0,
        note: "현재 다른 티켓 리뷰 중",
      },
      {
        type: "external",
        id: "ext-1",
        name: "박프론트",
        expertise: "React 전문",
        matchScore: 91,
        availability: "즉시 가용",
        costPerHour: 45,
        note: "유사 프로젝트 3건 경험",
      },
    ],
    selectedCandidate: "user-3",
  },
  {
    id: "hitl-5",
    type: "design_review",
    title: "이미지 공유 UI 디자인 검토",
    ticketId: "ticket-5",
    epicId: "epic-1",
    priority: "medium",
    status: "waiting",
    createdAt: "2026-04-03T08:00:00Z",
    requestedBy: "Dsn",
    assignedTo: { id: "user-1", name: "김CTO", level: "L3" },
    briefing:
      "Dsn Agent가 이미지 공유 UI 시안을 완성했습니다. 기존 디자인 시스템의 카드 컴포넌트 기반으로 작성했습니다.",
    designUrl: "https://figma.com/mock-design",
  },
  {
    id: "hitl-6",
    type: "model_allocation",
    title: "이미지 공유 기능 — AI 모델 배분 확인",
    epicId: "epic-1",
    priority: "high",
    status: "waiting",
    createdAt: "2026-04-03T08:30:00Z",
    requestedBy: "SM",
    assignedTo: { id: "user-1", name: "김CTO", level: "L3" },
    briefing: "이미지 공유 기능 개발에 투입될 AI 모델 배분을 확인해주세요.",
    allocation: {
      agents: [
        {
          agentId: "FE",
          models: [
            { model: "claude-sonnet-4", ratio: 0.78, estimatedInputTokens: 187200, estimatedOutputTokens: 66300, estimatedCost: 18.4 },
            { model: "gpt-4o", ratio: 0.15, estimatedInputTokens: 36000, estimatedOutputTokens: 12750, estimatedCost: 6.2 },
            { model: "gemini-2.0-flash", ratio: 0.07, estimatedInputTokens: 16800, estimatedOutputTokens: 5950, estimatedCost: 0.4 },
          ],
          totalCost: 25.0,
        },
        {
          agentId: "BE",
          models: [
            { model: "claude-sonnet-4", ratio: 0.9, estimatedInputTokens: 342000, estimatedOutputTokens: 108000, estimatedCost: 32.1 },
            { model: "gemini-2.0-flash", ratio: 0.1, estimatedInputTokens: 38000, estimatedOutputTokens: 12000, estimatedCost: 0.9 },
          ],
          totalCost: 33.0,
        },
        {
          agentId: "Dsn",
          models: [
            { model: "claude-sonnet-4", ratio: 0.55, estimatedInputTokens: 88000, estimatedOutputTokens: 33000, estimatedCost: 8.2 },
            { model: "gpt-4o", ratio: 0.45, estimatedInputTokens: 72000, estimatedOutputTokens: 27000, estimatedCost: 11.8 },
          ],
          totalCost: 20.0,
        },
        {
          agentId: "support",
          label: "지원 Agent (PM/GM/Pln/SM/HR/BM)",
          models: [
            { model: "gemini-2.0-flash", ratio: 0.8, estimatedCost: 1.2 },
            { model: "claude-haiku", ratio: 0.2, estimatedCost: 0.8 },
          ],
          totalCost: 2.0,
        },
      ],
      totalCost: 80.0,
      alternatives: [
        { id: "alt-current", label: "현재 구성 (권장)", totalCost: 80.0, qualityImpact: "none", recommended: true },
        { id: "alt-budget", label: "Sonnet → Haiku 전환", totalCost: 34.0, qualityImpact: "moderate_decrease" },
        { id: "alt-minimum", label: "전체 Flash 통일", totalCost: 12.0, qualityImpact: "significant_decrease" },
      ],
      smComment:
        "코드 생성 작업에 Sonnet을 집중 배치했습니다. 디자인 작업은 GPT-4o의 이미지 이해 능력을 활용합니다. 단순 분류/정리 작업은 Flash로 비용을 절감합니다.",
    },
  },
  // ─── cost_approval: 예산 초과 승인 ───
  {
    id: "hitl-7",
    type: "cost_approval",
    title: "커머스팀 4월 AI 비용 예산 초과 승인",
    ticketId: undefined,
    epicId: "epic-cm1-1",
    priority: "high",
    status: "waiting",
    createdAt: "2026-04-04T09:00:00Z",
    requestedBy: "BM",
    assignedTo: { id: "user-1", name: "김CTO", level: "L3" },
    briefing:
      "커머스팀 4월 AI 비용이 예산($400)의 92%($368)에 도달했습니다. 남은 에픽(상품 리뷰 시스템) 진행을 위해 $150 추가 예산을 요청합니다. 승인 시 4월 총 예산은 $550이 됩니다.",
    agentDiscussionSummary: "BM Agent 분석: 현 추세대로면 4월 말까지 $480 예상 소진. 추가 예산 없으면 4월 3주차부터 에이전트 일시정지 필요. PM Agent: 상품 리뷰 시스템은 5월 론칭에 필수이므로 예산 확보 권장.",
    costApproval: {
      currentBudget: 400,
      currentSpent: 368,
      requestedAdditional: 150,
      projectedTotal: 480,
      reason: "상품 리뷰 시스템 에픽 진행 + FE/BE Agent 비용 증가",
      breakdown: [
        { item: "FE Agent (리뷰 UI)", cost: 65 },
        { item: "BE Agent (리뷰 API)", cost: 55 },
        { item: "GM Agent (보안 검토)", cost: 15 },
        { item: "기타 (PM/SM 조율)", cost: 15 },
      ],
    },
  },
  // ─── cost_approval: 모델 업그레이드 비용 ───
  {
    id: "hitl-8",
    type: "cost_approval",
    title: "결제팀 모델 업그레이드 비용 승인",
    ticketId: "t-py1-3",
    epicId: "epic-py1-1",
    priority: "medium",
    status: "waiting",
    createdAt: "2026-04-04T11:00:00Z",
    requestedBy: "BM",
    assignedTo: { id: "user-1", name: "김CTO", level: "L3" },
    briefing:
      "간편결제 연동 작업의 복잡도가 예상보다 높아, BE Agent의 모델을 claude-haiku에서 claude-sonnet-4로 업그레이드해야 합니다. 일간 비용이 $12 → $35로 증가하며, 잔여 작업 기간(5일) 동안 추가 $115가 발생합니다.",
    agentDiscussionSummary: "SM Agent: 토스페이 연동 코드가 복잡해 haiku로는 오류율 40%. sonnet으로 전환하면 10% 이하로 낮출 수 있음. BM Agent: 5일간 $115 추가, 전체 결제팀 예산 대비 18% 증가.",
    costApproval: {
      currentBudget: 320,
      currentSpent: 185,
      requestedAdditional: 115,
      projectedTotal: 300,
      reason: "BE Agent 모델 업그레이드 (haiku → sonnet-4) — 간편결제 연동 정확도 향상",
      breakdown: [
        { item: "모델 비용 차이 (5일)", cost: 95 },
        { item: "재작업 방지 비용", cost: 20 },
      ],
    },
  },

  // ─── Context Change HITL ─────────────────────────────────

  {
    id: "hitl-ctx-1",
    type: "context_change",
    title: "마케팅 예산 증가 → 루틴 조정 및 티켓 우선순위 변경",
    epicId: "epic-gr-1",
    priority: "high",
    status: "waiting",
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    requestedBy: "BM",
    assignedTo: { id: "user-1", name: "김CTO", level: "L3" },
    briefing:
      "Notion 기획서에서 4분기 마케팅 예산 35% 증가가 감지되었습니다. BM Agent와 PM Agent가 작업 계획 조정을 제안합니다. 각 제안을 개별 승인하거나 거부해주세요.",
    agentDiscussionSummary: "BM Agent: 마케팅 비용 $12K→$16.2K(+35%), AI 분석 비용도 비례 증가 필요. PM Agent: 그로스팀 티켓 우선순위 조정으로 예산 효과 극대화 가능.",
    confidence: 82,
    riskLevel: "medium",
    evidenceNotes: [
      { metric: "마케팅 예산", current: "$12,000", proposed: "$16,200", impact: "positive" },
      { metric: "AI 운용 비용", current: "$280/월", proposed: "$380/월", impact: "negative" },
      { metric: "기대 ROI", current: "3.2x", proposed: "3.8x (예상)", impact: "positive" },
    ],
    contextChange: {
      eventId: "ctx-evt-1",
      eventType: "budget_change",
      summary: "4분기 마케팅 예산 35% 상향 조정됨 ($12K → $16.2K/월)",
      changes: [
        { metric: "마케팅 예산", before: "$12,000/월", after: "$16,200/월", delta: "+35%", impact: "positive" },
        { metric: "AI 비용 증가", before: "$280/월", after: "$380/월", delta: "+$100", impact: "negative" },
      ],
      proposals: [
        {
          id: "prop-ctx1-1",
          agentId: "agent-bm",
          agentLabel: "BM",
          proposalType: "routine_update",
          description: "마케팅 성과 분석 루틴: 주 2회 → 매일 실행",
          impact: "추가 비용 $8/월, 마케팅 반응 속도 3.5배 향상 예상",
          approved: undefined,
        },
        {
          id: "prop-ctx1-2",
          agentId: "agent-pm",
          agentLabel: "PM",
          proposalType: "ticket_priority",
          description: "그로스팀 콘텐츠 에픽 우선순위 High → Critical 상향 (3개 티켓 영향)",
          impact: "FE/BE Agent 배정 우선순위 변경, 2주 내 완료 목표",
          approved: undefined,
        },
      ],
    },
  },

  {
    id: "hitl-ctx-2",
    type: "context_change",
    title: "B2B API 서비스 출시 결정 → 신규 에픽 생성 제안",
    epicId: "epic-pf-1",
    priority: "critical",
    status: "waiting",
    createdAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    requestedBy: "PM",
    assignedTo: { id: "user-1", name: "김CTO", level: "L3" },
    briefing:
      "Notion 경영진 회의록에서 B2B API 서비스 2분기 출시 결정이 감지되었습니다. PM Agent가 신규 에픽 3개 생성과 기술 스펙 검토를 제안합니다.",
    agentDiscussionSummary: "PM Agent: B2B 전환을 위해 API 인증/문서화/과금 에픽 3개 필요. SM Agent: Kong API Gateway 또는 AWS API Gateway 중 선택 필요, 스펙 검토 우선 진행.",
    confidence: 91,
    riskLevel: "high",
    evidenceNotes: [
      { metric: "서비스 범위 변화", current: "B2C 전용", proposed: "B2C + B2B API", impact: "positive" },
      { metric: "신규 에픽 수", current: "0", proposed: "3개", impact: "neutral" },
      { metric: "예상 추가 공수", current: "—", proposed: "6~8주", impact: "negative" },
    ],
    contextChange: {
      eventId: "ctx-evt-2",
      eventType: "service_expansion",
      summary: "B2B API 서비스 2분기 출시 결정 (기존 B2C Only → B2C + B2B)",
      changes: [
        { metric: "서비스 범위", before: "B2C 전용", after: "B2C + B2B API", impact: "positive" },
        { metric: "신규 에픽", before: "—", after: "3개 (인증/문서/과금)", impact: "neutral" },
      ],
      proposals: [
        {
          id: "prop-ctx2-1",
          agentId: "agent-pm",
          agentLabel: "PM",
          proposalType: "epic_create",
          description: "신규 에픽 3개 생성: B2B API 인증 시스템 / API 문서화 포털 / B2B 과금·정산 모듈",
          impact: "플랫폼팀에 6~8주 추가 작업. 티켓 40~60개 예상",
          approved: undefined,
        },
        {
          id: "prop-ctx2-2",
          agentId: "agent-sm",
          agentLabel: "SM",
          proposalType: "epic_create",
          description: "API 게이트웨이 기술 스펙 검토 (Kong vs AWS API GW) 및 spec_decision HITL 생성",
          impact: "스펙 결정 후 에픽 상세 설계 진행, 1주 소요",
          approved: undefined,
        },
      ],
    },
  },
];
