import { Project, Epic, Ticket } from "@/types/project";

export const DUMMY_PROJECTS: Project[] = [
  {
    id: "proj-1",
    name: "SNS 서비스 v2.0",
    description: "소셜 네트워크 서비스 전면 리뉴얼",
    startDate: "2026-03-01",
    endDate: "2026-06-30",
    memberCount: 12,
    status: "active",
  },
  {
    id: "proj-2",
    name: "결제 시스템 마이그레이션",
    description: "PG사 변경에 따른 결제 모듈 전면 교체",
    startDate: "2026-04-01",
    endDate: "2026-05-15",
    memberCount: 6,
    status: "active",
  },
];

export const DUMMY_EPICS: Record<string, Epic[]> = {
  "proj-1": [
    {
      id: "epic-1",
      projectId: "proj-1",
      title: "이미지 공유 기능",
      description: "사용자가 이미지를 업로드하고 피드에 공유하는 기능",
      status: "in_progress",
      priority: "high",
      ticketCount: 6,
      completedTickets: 2,
      estimatedCost: 245.0,
      estimatedDays: 14,
    },
    {
      id: "epic-2",
      projectId: "proj-1",
      title: "피드 알고리즘 개선",
      description: "개인화 추천 피드 알고리즘 v2",
      status: "backlog",
      priority: "medium",
      ticketCount: 4,
      completedTickets: 0,
      estimatedCost: 180.0,
      estimatedDays: 10,
      dependsOn: ["epic-1"],
    },
    {
      id: "epic-3",
      projectId: "proj-1",
      title: "성능 최적화",
      description: "API 응답 속도 및 프론트엔드 번들 최적화",
      status: "backlog",
      priority: "low",
      ticketCount: 3,
      completedTickets: 0,
      estimatedCost: 120.0,
      estimatedDays: 7,
    },
  ],
};

export const DUMMY_TICKETS: Record<string, Ticket[]> = {
  "epic-1": [
    {
      id: "ticket-1",
      epicId: "epic-1",
      title: "이미지 업로드 API 개발",
      description: "S3 + CDN 기반 이미지 업로드 엔드포인트 구현",
      status: "done",
      priority: "high",
      assignedAgent: "BE",
      assignedHuman: null,
      estimatedHours: 16,
      actualHours: 14,
      costUsd: 42.0,
      subtaskIds: ["sub-1", "sub-2", "sub-3"],
    },
    {
      id: "ticket-2",
      epicId: "epic-1",
      title: "이미지 리사이징 파이프라인",
      description: "업로드된 이미지 자동 리사이징 + 썸네일 생성",
      status: "done",
      priority: "high",
      assignedAgent: "BE",
      assignedHuman: null,
      estimatedHours: 12,
      actualHours: 10,
      costUsd: 30.0,
    },
    {
      id: "ticket-3",
      epicId: "epic-1",
      title: "ImageUploader 컴포넌트 개발",
      description: "프론트엔드 이미지 업로드 + 미리보기 컴포넌트",
      status: "review",
      priority: "high",
      assignedAgent: "FE",
      assignedHuman: { id: "user-3", name: "김주니어", level: "L1" },
      estimatedHours: 8,
      hitlRequired: true,
      hitlType: "code_review",
    },
    {
      id: "ticket-4",
      epicId: "epic-1",
      title: "공유 링크 생성 API",
      description: "이미지 공유용 단축 URL 생성 로직",
      status: "in_progress",
      priority: "medium",
      assignedAgent: "BE",
      assignedHuman: null,
      estimatedHours: 6,
      costUsd: 18.0,
    },
    {
      id: "ticket-5",
      epicId: "epic-1",
      title: "이미지 뷰어 UI",
      description: "피드 내 이미지 확대/스와이프 뷰어",
      status: "todo",
      priority: "medium",
      assignedAgent: "FE",
      assignedHuman: null,
      estimatedHours: 10,
      dependsOn: ["ticket-3"],
    },
    {
      id: "ticket-6",
      epicId: "epic-1",
      title: "보안 검토",
      description: "이미지 업로드 관련 보안 정책 검토",
      status: "in_progress",
      priority: "high",
      assignedAgent: "GM",
      assignedHuman: null,
      estimatedHours: 4,
      hitlRequired: true,
      hitlType: "security_approval",
    },
  ],
};
