import { Skill, SkillDocument, SkillUsageSummary } from "@/types/skill";

export const DUMMY_SKILLS: Skill[] = [
  // ── 전사 공통 ──
  {
    id: "skill-1",
    title: "코드 리뷰 — 보안 관점",
    description: "OWASP Top 10 기준으로 코드 보안 취약점을 분석하고 수정 방향을 제안합니다.",
    category: "code_review",
    scope: "global",
    agentIds: ["GM", "BE", "FE"],
    usageCount: 42,
    avgCostUsd: 0.8,
    avgDurationMin: 4,
    successRate: 97,
    createdAt: "2026-01-10T09:00:00Z",
    tags: ["보안", "OWASP", "코드리뷰"],
    promptPreview: "다음 코드를 OWASP Top 10 기준으로 검토하고 취약점과 수정 방향을 제안하세요...",
  },
  {
    id: "skill-2",
    title: "TypeScript 타입 정의 생성",
    description: "API 응답 JSON 또는 DB 스키마를 입력받아 TypeScript 타입/인터페이스를 자동 생성합니다.",
    category: "code_review",
    scope: "global",
    agentIds: ["FE", "BE", "SM"],
    usageCount: 78,
    avgCostUsd: 0.3,
    avgDurationMin: 2,
    successRate: 99,
    createdAt: "2026-01-15T09:00:00Z",
    tags: ["TypeScript", "타입", "자동화"],
    promptPreview: "다음 JSON 구조를 분석하여 TypeScript 인터페이스를 생성하세요...",
  },
  {
    id: "skill-3",
    title: "기술 스펙 문서 초안 작성",
    description: "기능 요구사항을 바탕으로 기술 스펙 문서(아키텍처 결정, 인터페이스 설계, 구현 방향)를 작성합니다.",
    category: "spec_writing",
    scope: "global",
    agentIds: ["SM", "Pln"],
    usageCount: 31,
    avgCostUsd: 2.1,
    avgDurationMin: 12,
    successRate: 90,
    createdAt: "2026-02-01T09:00:00Z",
    tags: ["스펙", "아키텍처", "문서화"],
    promptPreview: "다음 기능 요구사항을 기반으로 기술 스펙 문서를 작성하세요...",
  },
  {
    id: "skill-4",
    title: "단위 테스트 자동 생성",
    description: "함수/컴포넌트 코드를 입력받아 Jest/Vitest 기반 단위 테스트를 생성합니다. 엣지 케이스 포함.",
    category: "test_generation",
    scope: "global",
    agentIds: ["FE", "BE"],
    usageCount: 65,
    avgCostUsd: 0.6,
    avgDurationMin: 5,
    successRate: 94,
    createdAt: "2026-02-10T09:00:00Z",
    tags: ["테스트", "Jest", "Vitest", "자동화"],
    promptPreview: "다음 함수에 대한 단위 테스트를 작성하세요. 엣지 케이스와 실패 케이스를 포함합니다...",
  },
  {
    id: "skill-5",
    title: "API 엔드포인트 문서화 (OpenAPI)",
    description: "Express/Fastify 라우터 코드를 분석하여 OpenAPI 3.0 스펙을 자동 생성합니다.",
    category: "documentation",
    scope: "global",
    agentIds: ["BE"],
    usageCount: 29,
    avgCostUsd: 1.2,
    avgDurationMin: 8,
    successRate: 96,
    createdAt: "2026-02-15T09:00:00Z",
    tags: ["OpenAPI", "Swagger", "REST", "문서화"],
    promptPreview: "다음 라우터 코드를 분석하여 OpenAPI 3.0 형식의 API 문서를 생성하세요...",
  },
  {
    id: "skill-6",
    title: "레거시 코드 리팩토링 계획",
    description: "레거시 코드를 분석하고 단계적 리팩토링 계획(우선순위, 리스크, 예상 공수)을 수립합니다.",
    category: "refactoring",
    scope: "global",
    agentIds: ["SM", "FE", "BE"],
    usageCount: 18,
    avgCostUsd: 3.4,
    avgDurationMin: 20,
    successRate: 88,
    createdAt: "2026-03-01T09:00:00Z",
    tags: ["리팩토링", "레거시", "마이그레이션"],
    promptPreview: "다음 레거시 코드를 분석하고 단계적 리팩토링 계획을 수립하세요...",
  },
  // ── 커머스팀 ──
  {
    id: "skill-7",
    title: "상품 데이터 정합성 검증",
    description: "상품 DB 스키마와 실제 데이터를 비교하여 정합성 오류를 찾고 수정 쿼리를 생성합니다.",
    category: "data_analysis",
    scope: "team",
    teamId: "team-commerce",
    agentIds: ["BE", "GM"],
    usageCount: 12,
    avgCostUsd: 1.5,
    avgDurationMin: 10,
    successRate: 100,
    createdAt: "2026-03-10T09:00:00Z",
    tags: ["상품", "데이터검증", "SQL"],
  },
  {
    id: "skill-8",
    title: "A/B 테스트 결과 분석",
    description: "A/B 테스트 로그 데이터를 분석하고 통계적 유의미성과 비즈니스 임팩트를 요약합니다.",
    category: "data_analysis",
    scope: "team",
    teamId: "team-commerce",
    agentIds: ["BE"],
    usageCount: 7,
    avgCostUsd: 2.2,
    avgDurationMin: 15,
    successRate: 100,
    createdAt: "2026-03-15T09:00:00Z",
    tags: ["A/B테스트", "통계", "분석"],
  },
  // ── 플랫폼팀 ──
  {
    id: "skill-9",
    title: "CI/CD 파이프라인 최적화",
    description: "GitHub Actions 워크플로우를 분석하고 캐싱, 병렬화, 불필요한 스텝 제거로 빌드 시간을 단축합니다.",
    category: "refactoring",
    scope: "team",
    teamId: "team-platform",
    agentIds: ["BE", "SM"],
    usageCount: 5,
    avgCostUsd: 1.8,
    avgDurationMin: 12,
    successRate: 80,
    createdAt: "2026-03-20T09:00:00Z",
    tags: ["CI/CD", "GitHub Actions", "DevOps"],
  },
  {
    id: "skill-10",
    title: "인프라 비용 분석 리포트",
    description: "클라우드 사용량 데이터를 분석하여 비용 절감 기회와 최적화 방향을 제안합니다.",
    category: "data_analysis",
    scope: "team",
    teamId: "team-platform",
    agentIds: ["BM", "BE"],
    usageCount: 3,
    avgCostUsd: 2.8,
    avgDurationMin: 18,
    successRate: 100,
    createdAt: "2026-03-25T09:00:00Z",
    tags: ["클라우드", "비용최적화", "AWS"],
  },
];

export const DUMMY_SKILL_DOCUMENTS: SkillDocument[] = [
  {
    id: "doc-1",
    title: "이미지 공유 기능 API 문서",
    type: "api_docs",
    generatedBy: ["BE"],
    ticketId: "ticket-6",
    projectId: "proj-cm-1",
    status: "ready",
    createdAt: "2026-04-02T16:00:00Z",
    updatedAt: "2026-04-03T09:00:00Z",
    sizeKb: 48,
    pageCount: 6,
    tags: ["API", "이미지", "REST"],
  },
  {
    id: "doc-2",
    title: "상품 상세 리뉴얼 아키텍처 문서",
    type: "architecture",
    generatedBy: ["SM", "BE"],
    projectId: "proj-cm-1",
    status: "ready",
    createdAt: "2026-03-10T10:00:00Z",
    updatedAt: "2026-03-15T14:00:00Z",
    sizeKb: 124,
    pageCount: 18,
    tags: ["아키텍처", "상품", "리뉴얼"],
  },
  {
    id: "doc-3",
    title: "PG 연동 v2 온보딩 가이드",
    type: "onboarding",
    generatedBy: ["SM", "Pln"],
    projectId: "proj-py-1",
    status: "outdated",
    createdAt: "2026-02-15T09:00:00Z",
    updatedAt: "2026-02-20T11:00:00Z",
    sizeKb: 72,
    pageCount: 10,
    tags: ["PG", "온보딩", "결제"],
  },
  {
    id: "doc-4",
    title: "CI/CD 파이프라인 런북",
    type: "runbook",
    generatedBy: ["BE", "SM"],
    projectId: "proj-pf-1",
    status: "ready",
    createdAt: "2026-03-25T14:00:00Z",
    updatedAt: "2026-04-01T10:00:00Z",
    sizeKb: 56,
    pageCount: 8,
    tags: ["CI/CD", "DevOps", "운영"],
  },
  {
    id: "doc-5",
    title: "ImageUploader 마이그레이션 가이드",
    type: "migration_guide",
    generatedBy: ["FE", "SM"],
    ticketId: "ticket-3",
    projectId: "proj-cm-1",
    status: "generating",
    createdAt: "2026-04-03T10:00:00Z",
    updatedAt: "2026-04-03T10:00:00Z",
    sizeKb: 0,
    pageCount: 0,
    tags: ["마이그레이션", "컴포넌트", "FE"],
  },
];

export const DUMMY_SKILL_USAGE_SUMMARY: SkillUsageSummary = {
  totalUsage: 290,
  totalCostUsd: 187.4,
  thisMonthUsage: 94,
  thisMonthCostUsd: 62.1,
  topSkills: [
    { skillId: "skill-2", title: "TypeScript 타입 정의 생성", usageCount: 78, costUsd: 23.4 },
    { skillId: "skill-4", title: "단위 테스트 자동 생성", usageCount: 65, costUsd: 39.0 },
    { skillId: "skill-1", title: "코드 리뷰 — 보안 관점", usageCount: 42, costUsd: 33.6 },
    { skillId: "skill-3", title: "기술 스펙 문서 초안 작성", usageCount: 31, costUsd: 65.1 },
    { skillId: "skill-5", title: "API 엔드포인트 문서화", usageCount: 29, costUsd: 34.8 },
  ],
  agentBreakdown: [
    { agentId: "FE", usageCount: 89, costUsd: 48.2 },
    { agentId: "BE", usageCount: 76, costUsd: 52.1 },
    { agentId: "SM", usageCount: 55, costUsd: 41.3 },
    { agentId: "GM", usageCount: 32, costUsd: 18.4 },
    { agentId: "Pln", usageCount: 28, costUsd: 14.6 },
    { agentId: "BM", usageCount: 10, costUsd: 12.8 },
  ],
};
